# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 31, 1, "", "inference.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0finference.proto\x12\tinference"J\n\tImageData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x04 \x01(\x05"\xd1\x01\n\x10InferenceRequest\x12\x12\n\nepisode_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x03(\x02\x12)\n\x0bhead_camera\x18\x03 \x01(\x0b\x32\x14.inference.ImageData\x12/\n\x11left_wrist_camera\x18\x04 \x01(\x0b\x32\x14.inference.ImageData\x12\x30\n\x12right_wrist_camera\x18\x05 \x01(\x0b\x32\x14.inference.ImageData\x12\x0c\n\x04task\x18\x06 \x01(\t"O\n\x11InferenceResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nprediction\x18\x02 \x03(\x02\x12\x12\n\nepisode_id\x18\x03 \x01(\t2X\n\x10InferenceService\x12\x44\n\x07Predict\x12\x1b.inference.InferenceRequest\x1a\x1c.inference.InferenceResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "inference_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_IMAGEDATA"]._serialized_start = 30
    _globals["_IMAGEDATA"]._serialized_end = 104
    _globals["_INFERENCEREQUEST"]._serialized_start = 107
    _globals["_INFERENCEREQUEST"]._serialized_end = 316
    _globals["_INFERENCERESPONSE"]._serialized_start = 318
    _globals["_INFERENCERESPONSE"]._serialized_end = 397
    _globals["_INFERENCESERVICE"]._serialized_start = 399
    _globals["_INFERENCESERVICE"]._serialized_end = 487
# @@protoc_insertion_point(module_scope)
